import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { builtinModules } from "node:module";

/** 开发模式 banner（Obsidian 官方模板措辞，便于贡献者识别产物来源） */
export const DEV_BANNER =
	"/*!\n" +
	" * This file was automated-generated by esbuild for development.\n" +
	" * Do not edit it directly.\n" +
	" */";

/**
 * 发布模式 banner。刻意不带版本号——版本以 manifest.json 为唯一事实源，
 * 写进 banner 会制造第二个需要同步的版本副本（正是 release 闸门要防的事）。
 */
export const RELEASE_BANNER =
	"/*!\n" +
	" * Code Converter — production build generated by esbuild.\n" +
	" * Do not edit directly. Repository: https://github.com/xiaosong8584/code-converter\n" +
	" * @license MIT\n" +
	" */";

/** 运行时由 Obsidian 提供，绝不打包（Obsidian 插件铁律） */
export const EXTERNAL = ["obsidian", "electron", "@codex", "lodash"];

/**
 * esbuild 插件：外部化 obsidian/electron/lodash 与所有 Node 内置模块。
 * 单独抽出是因为配置在构建与 watch 两条路径共用。
 */
function makePlugins() {
	return [
		{
			name: "externalize-deps",
			setup(build) {
				build.onResolve({ filter: /^obsidian|electron|@codex|lodash/ }, (args) => ({
					path: args.path,
					external: true
				}));
			}
		},
		{
			name: "externalize-node-builtin",
			setup(build) {
				build.onResolve({ filter: /.*/ }, (args) => {
					if (builtinModules.includes(args.path)) {
						return { path: args.path, external: true };
					}
					if (args.path.startsWith("node:")) {
						return { path: args.path, external: true };
					}
				});
			}
		}
	];
}

/**
 * 打包配置（唯一事实源）。
 *
 * @param {boolean} release 发布模式：压缩、不产 sourcemap、输出到 dist/main.js。
 *   开发模式保留 inline sourcemap 并输出到仓库根的 main.js。
 * @returns {esbuild.BuildOptions}
 */
export function buildConfig(release = false) {
	return {
		banner: {
			js: release ? RELEASE_BANNER : DEV_BANNER
		},
		bundle: true,
		entryPoints: ["src/main.ts"],
		external: EXTERNAL,
		logLevel: "info",
		platform: "node",
		target: "es2020",
		outfile: release ? path.join("dist", "main.js") : "main.js",
		plugins: makePlugins(),
		sourcemap: release ? false : "inline",
		// 只有关闭发布模式才压缩；开发模式保留可读性便于定位问题
		minify: release
	};
}

/**
 * 执行一次构建（单次 rebuild 后释放 context）。
 *
 * @param {boolean} release 同 {@link buildConfig}
 * @returns {Promise<string>} 产物相对路径
 */
export async function build(release = false) {
	const config = buildConfig(release);
	const context = await esbuild.context(config);
	try {
		await context.rebuild();
	} finally {
		await context.dispose();
	}
	process.stdout.write(`\n${config.banner.js}\n`);
	return config.outfile;
}

/**
 * 启动 watch 模式。只能在开发模式下用（发布产物不应当常驻监听）。
 * 调用后不返回——常驻直到收到 Ctrl+C。
 */
export async function watch() {
	const context = await esbuild.context(buildConfig(false));
	await context.watch();
}

/**
 * 判断本模块是否为直接入口（而非被 import）。
 *
 * 必须用 realpath 归一化后再比：Windows 上工作区常经 junction 访问（如
 * `C:\Users\…\2026-09-16-23-57-50` 实际指向 `I:\Users\…`），此时
 * `path.resolve(process.argv[1])` 给出 junction 路径（C:）、而
 * `fileURLToPath(import.meta.url)` 给出真实盘符路径（I:），**直接字符串比较
 * 恒为 false**——守卫静默失效、`npm run build` 不产出任何文件也不报错，是最难
 * 排查的一类故障。realpath 两侧都落到真实盘符后即可正确相等。
 */
function isMainModule() {
	const entry = process.argv[1];
	if (!entry) return false;
	const canonical = (p) => {
		try {
			return realpathSync(p);
		} catch {
			return p;
		}
	};
	return canonical(path.resolve(entry)) === canonical(fileURLToPath(import.meta.url));
}

/**
 * 主模块守卫：`node scripts/build.mjs` 直接运行时执行构建；
 * 被 `import` 时（scripts/release.mjs）只导出 API、不产生副作用。
 * 这样 release 流程无需 spawn 子进程——沙箱内 spawn 同一个受管 node 会 EBUSY。
 */
if (isMainModule()) {
	const hasWatch = process.argv.includes("--watch");
	const hasRelease = process.argv.includes("--release");
	if (hasWatch && hasRelease) {
		// 两个互斥模式同时传入时静默忽略会让用户拿到错误的产物，必须显式失败
		console.error("错误：--watch 与 --release 互斥，不能同时使用。");
		process.exitCode = 1;
	} else if (hasWatch) {
		await watch();
	} else {
		await build(hasRelease);
	}
}
