import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
	"/*!\n" +
	" * This file was automated-generated by esbuild for development.\n" +
	" * Do not edit it directly.\n" +
	" */";

const production = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const plugins = [
	// Obsidian 打包插件的通用 banner
	{
		name: "banner",
		setup(build) {
			build.onEnd(() => {
				process.stdout.write(
					`\n${banner}\n`
				);
			});
		}
	},
	// obsidian / electron / node 内置模块作为外部依赖
	{
		name: "externalize-deps",
		setup(build) {
			build.onResolve({ filter: /^obsidian|electron|@codex|lodash/ }, (args) => ({
				path: args.path,
				external: true
			}));
		}
	},
	// Node 内置模块外部化
	{
		name: "externalize-node-builtin",
		setup(build) {
			build.onResolve({ filter: /.*/ }, (args) => {
				if (builtins.includes(args.path)) {
					return { path: args.path, external: true };
				}
				if (args.path.startsWith("node:")) {
					return { path: args.path, external: true };
				}
			});
		}
	}
];

const context = await esbuild.context({
	banner: {
		js: banner
	},
	bundle: true,
	entryPoints: ["src/main.ts"],
	external: [
		"obsidian",
		"electron",
		"@codex",
		"lodash"
	],
	logLevel: "info",
	platform: "node",
	target: "es2022",
	outfile: "main.js",
	plugins: plugins,
	sourcemap: production ? false : "inline"
});

if (watch) {
	await context.watch();
} else {
	await context.rebuild();
	await context.dispose();
}
